---
  - name: Converge
    hosts: all
    become: true

    vars:
      ssh_chroot_l2chroot_path: /usr/bin/l2chroot
      ssh_chroot_jail_users:
        - name: foo
          home: /home/foo
          shell: /bin/bash

    roles:
      - role: buluma.ssh_chroot_jail
