---
- name: Converge
  hosts: all
  become: true

  vars:
    ssh_chroot_l2chroot_path: /usr/bin/l2chroot
    ssh_chroot_jail_users:
      - name: foo
        home: /home/foo
        shell: /bin/bash

  pre_tasks:
    - name: update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Ensure build dependencies are installed.
      ansible.builtin.package:
        name:
          - ed
          - nano
          - vim
          - coreutils
        state: present

    - name: ensure build dependencies are installed (RedHat).
      ansible.builtin.package:
        name:
          - openssh-server
          - openssh-clients
        state: present
      when: ansible_os_family == 'RedHat'

    - name: ensure build dependencies are installed (Debian).
      ansible.builtin.apt:
        name:
          - openssh-server
          - openssh-client
        state: present
      when: ansible_os_family == 'Debian'

  roles:
    - role: ansible-role-ssh_chroot_jail
